COMPONENT=ClientAppC
CFLAGS += -I$(TOSDIR)/lib/printf
CFLAGS += -I../Common
CFLAGS += -I../Common/PublishModule
CFLAGS += -I../Common/QueueSender
CFLAGS += -I./SubscribeModule
CFLAGS += -I./ConnectionModule
CFLAGS += -I./PublishModule
#CFLAGS += -DNEW_PRINTF_SEMANTICS

include $(MAKERULES)

