COMPONENT=ServerAppC
CFLAGS += -I$(TOSDIR)/lib/printf
CFLAGS += -I../Common
CFLAGS += -I./SubscribeModule
CFLAGS += -I./ConnectionModule
CFLAGS += -I./PublishModule
CFLAGS += -I./PublishQueueSender
#CFLAGS += -DNEW_PRINTF_SEMANTICS

include $(MAKERULES)

