COMPONENT=ServerAppC
CFLAGS += -I$(TOSDIR)/lib/printf
CFLAGS += -I../Common
CFLAGS += -I../Common/PublishModule
CFLAGS += -I../Common/QueueSender
CFLAGS += -I./SubscribeModule
CFLAGS += -I./ConnectionModule
CFLAGS += -I./PublishModule
CFLAGS += -I./QueueSender
#CFLAGS += -DNEW_PRINTF_SEMANTICS

include $(MAKERULES)

