#ifndef CONSTANTS_H
#define CONSTANTS_H
typedef enum {
	UNUSED,
	CONNECT_AM,
	
	SUBSCRIBE_AM,
	SUBACK_AM,
	PUBLISH_AM,

}packet_channel;


#define N_NODES 8
#define PANC_ID 1
#define TEMP_MASK 1
#define HUMI_MASK 2
#define LUMI_MASK 4
#define TEMP_ALLIGNMENT 0
#define HUMI_ALLIGNMENT 1
#define LUMI_ALLIGNMENT 2
#define MAXQUEUELENGHT N_NODES*N_NODES
#define TIMEBETWEENMESSAGES 100

#define SENSOR_TIMER 1000
#define TEMPERATURE_DELAY 10
#define HUMIDITY_DELAY 20
#define LUMINOSITY_DELAY 50

enum {
	NO_TOPIC,
	TEMPERATURE,
	HUMIDITY,
	LUMINOSITY
};


#endif
